version: "3"
services:
  ws:
    build: .
    depends_on:
      - redis
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
    networks:
      - go_ws_network

  redis:
    image: redis:latest
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - type: bind
        source: ./redis.conf
        target: /etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - go_ws_network

volumes:
  redis_go_ws_volume:
    name: redis_go_ws_volume

networks:
  go_ws_network:
    external: true
